---
title: "ST558_Project2_Group_2H"
output: github_document
author: "Manan Shah, Xi Yang"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(jsonlite)
library(httr)
library(plotly)
```

```{r}
Tickers <- function(type="CS",sort="ticker",order="asc",limit=10){
  
  base <- "https://api.polygon.io/v3/reference/tickers?type="
  type <- type
  sort <- sort
  order <- order
  limit <- limit
  
  url <- paste(base,type,"&sort=",sort,"&order=",order,"&limit=",limit,"&apiKey=OSOTVVjvsUEE8FFAyyX0n3XnWMpFdZv7",sep="")

  data <- GET(url)
  
  parsed <- fromJSON(rawToChar(data$content))
  
  # parsed$results <- parsed$results %>% drop_na(c("primary_exchange"))
  
  parsed$results <- as_tibble(parsed$results)
  
  parsed$results <- within(parsed$results, primary_exchange[market == "otc"] <- "OTC")

  return(parsed$results)
}
Tickers("ETF", "ticker", "asc", 50)
```

```{r}
ticker_from_names <- function(ticker_name){
  data <- GET("https://api.polygon.io/v3/reference/tickers?active=true&sort=ticker&order=asc&apiKey=OSOTVVjvsUEE8FFAyyX0n3XnWMpFdZv7")
  
  parsed <- fromJSON(rawToChar(data$content))

  result <- as_tibble(parsed$results)

  result <- result %>% filter(name == ticker_name)
  
  return(as.character(result[,c("ticker")]))
}
ticker_from_names("AAREAL BANK AG UNSP/ADR")
```


```{r}
rmarkdown::render(input = "ST558_Project2_Group_2H.Rmd", output_file = "ST558_Group_2H.md")
```

### 4 Get the daily open, high, low, and close (OHLC) for the entire stocks/equities markets.
```{r echo=TRUE,eval=TRUE}
library(jsonlite)
library(httr)
library(tidyverse)
groupedDaily<-function(year=2022, month=10, day=07){
  #Define base combination in url
  base <- "https://api.polygon.io/v2/aggs/grouped/locale/us/market/stocks/"
  #Define Year Input
  Year<-as.character(year)
  #Define Month Input
  if(month<10){
    Month<-paste("0",as.character(month),sep="")
  }
  else{
    Month<-as.character(month)
  }
  #Define Day Input
    if(day<10){
    Day<-paste("0",as.character(day),sep="")
  }
  else{
    Day<-as.character(day)
  }
  Date<-as.Date(paste(Year,Month,Day,sep="-"))
if(grepl("S(at|un)", weekdays(Date))){
   message<- paste("ERROR: The input date is a weekend, there is no data available")
  stop(message)
}
  else{
    url <- paste(base,Date,"?adjusted=true&apiKey=woI7TWx23Hf4JkX9Rghf7tvlpaF3jVma",sep="")
  data <- GET(url)
  parsed <- fromJSON(rawToChar(data$content))
  result <- as_tibble(parsed$results)
  Movement <- if_else(result$o <  result$c, "Up", "Down")
  result$Movement <- Movement
  return(result)
  }
}
groupedDaily()
```  
### 5 Get the previous day's open, high, low, and close (OHLC) for the specified stock ticker.
```{r echo=TRUE,eval=TRUE}
library(jsonlite)
library(httr)
library(tidyverse)
previousClose<-function(stockTicker="AAPL"){
  #Define base combination in url
  base <- "https://api.polygon.io/v2/aggs/ticker/"
  #Define stockTiker Input
  StockTicker<-stockTicker
    url <- paste(base,StockTicker,"/prev?adjusted=true&apiKey=woI7TWx23Hf4JkX9Rghf7tvlpaF3jVma",sep="")
  data <- GET(url)
  parsed <- fromJSON(rawToChar(data$content))
  return(as_tibble(parsed$results))
}
previousClose()
``` 

```{r}
stock_price <- function(name_or_ticker, stock, from, to){
  x <- name_or_ticker
  if (x == "name"){
    ticker <- ticker_from_names(stock)
  }
  else{
    ticker <- stock
  }
  
  base_1 <- "https://api.polygon.io/v2/aggs/ticker/"
  base_2 <- "/range/1/day/"
  base_3 <- "?adjusted=true&limit=50&apiKey=OSOTVVjvsUEE8FFAyyX0n3XnWMpFdZv7"
  
  url <- paste(base_1, ticker, base_2, from, "/", to, base_3, sep = "")
  data <- GET(url)
  parsed <- fromJSON(rawToChar(data$content))
  return(as_tibble(parsed$results))
}
stock_price("ticker", "AAPL", "2021-07-22", "2022-07-22")
```

EDA
```{r}
data <- list(Tickers("ETF", "ticker", "asc", 500), stock_price("ticker", "AAPL", "2021-07-22", "2022-07-22"))

data_new_variable <- data[[2]]
Movement <- if_else(data_new_variable$o < data_new_variable$c, "Up", "Down")
data_new_variable$Movement <- Movement
data_new_variable

contingency_data <- data[[1]]
contingency_data$market <- as.factor(contingency_data$market)
contingency_data$primary_exchange <- as.factor(contingency_data$primary_exchange)
contingency_table <- table(contingency_data$market, contingency_data$primary_exchange)
contingency_table

data_1 <- data[[1]]
bar_plot_data <- data_1 %>% count(primary_exchange)
bar_plot <- ggplot(data = bar_plot_data, aes(primary_exchange, n)) + labs(y = "Count of ETF") + geom_bar(stat = "identity", fill = "steelblue")
bar_plot

data_2 <- data[[2]]
hist_plot_data <- data_2 %>% select(o)
hist_plot <- ggplot(data = hist_plot_data, aes(o)) + labs(x = "Open Price", y = "Count") + geom_histogram(color="black", fill="grey")
hist_plot

data_3 <- data_new_variable
box_plot_data <- data_3 %>% select(Movement, o)
box_plot <- ggplot(box_plot_data, aes(x = Movement, y = o))  + labs(title = "Boxplot for Movement") + geom_boxplot()
box_plot

data_4 <- data[[2]]
candlestick_plot_data <- mutate(data_4, date =  as.POSIXct(data_4$t/1000, origin="1970-01-01"))
candlestick_plot_data
candlestick_plot <- candlestick_plot_data %>% plot_ly(x = date, type = "candlestick", open = o, close = c, high = h, low = l)
```
### EDA2
```{r echo=TRUE, eval=TRUE}
library(tidyverse)
groupedDaily() %>%
  filter(n>=100000) %>%
  group_by(Movement) %>%
  arrange(desc(n)) %>% 
  summarise(Avg=mean(h),Sd=sd(h),Median=median(h),IQR=IQR(h))
```


```{r echo=TRUE, eval=TRUE}
popularData<- groupedDaily() %>%
  filter(n>100000) %>%
  arrange(desc(n))
popularData
g<- ggplot(popularData, aes(x=l, y=n))
g+geom_point(aes(col=n))+
  labs(title="Number of Transaction vs low price", x = "Low Price", y = "Number of Transactions")
```

